### ISSUE TITLE
Suggested query: List pathways without curation tags

### ISSUE THREAD

**Issue by khanspers** [wikipathways/SPARQLQueries#10]
Sometimes I find pathways that don't have any curation tags, so even if they are actually complete, they are not included in the analysis set. Also, since they don't have any other tags, they don't show up in the admin curation protocol. So they are effectively invisible. Is it possible to create a SPARQL query to find them?

**Comment by egonw** [comment]
No (something I only realized now), because the convertor only converts `Curated` and `Reactome` into RDF.

**Comment by egonw** [comment]
Okay, it was late... yes, for the release RDF I was right, but of course, with the RDF for all pathways, not. It seems to work:

![image](https://user-images.githubusercontent.com/26721/106269960-8a672d00-622d-11eb-88d1-0097f37af51d.png)

You can find them here: https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20Expert%20Curation%20-%20Daily%20All/lastCompletedBuild/testReport/ 

And then look in that list for `General.noTag`.
